# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'iOSCalcultor' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for iOSCalcultor

  target 'iOSCalcultorTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'iOSCalcultorUITests' do
    # Pods for testing
  end
pod'Masonry'
end
